-- ============================================================
-- Project: Teacher Dashboard (Oracle APEX)
-- Description: Core schema objects for teacher profiles,
--              class schedule, and weekly timetable tracking
-- Author:Syed 
-- ============================================================

-- 1. Table for storing teacher profiles
CREATE TABLE TBLTEACHERS (
    STAFFID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIRSTNAME        VARCHAR2(100),
    LASTNAME         VARCHAR2(100),
    EMAIL            VARCHAR2(200),
    PHONENUMBER      VARCHAR2(50),
    FACEBOOK         VARCHAR2(255),
    LINKEDIN         VARCHAR2(255),
    SKYPE            VARCHAR2(100),
    PROFILE_IMAGE    VARCHAR2(500),
    DATECREATED      DATE DEFAULT SYSDATE
);

-- 2. Table for storing teacher class schedules
CREATE TABLE TBLCLASS_SCHEDULE (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STAFFID          NUMBER REFERENCES TBLTEACHERS(STAFFID),
    CLASS_DATE       DATE,
    START_TIME       VARCHAR2(10),
    END_TIME         VARCHAR2(10),
    SUBJECT          VARCHAR2(200),
    ROOM_NO          VARCHAR2(50),
    STATUS           VARCHAR2(50)
);

-- 3. Table for tracking weekly timetable (summary view)
CREATE TABLE TBLWEEKLY_TIMETABLE (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STAFFID          NUMBER REFERENCES TBLTEACHERS(STAFFID),
    WEEK_START_DATE  DATE,
    WEEK_END_DATE    DATE,
    TOTAL_CLASSES    NUMBER,
    CREATED_AT       DATE DEFAULT SYSDATE
);

-- 4. Sample data (optional)
INSERT INTO TBLTEACHERS (FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER)
VALUES ('Sidra', 'Khan', 'sidra.khan@example.com', '03001234567');

COMMIT;
